# Generated by Django 3.2.4 on 2021-07-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='date',
        ),
    ]
